[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "096d1c408ead00e2331ab79732057c4fad62552e"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "c2334d7222e3d27266af02ce65d16cc1c4485faa059d49585757312f0899b10a"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-linux-gnu-cxx03.tar.gz"
[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5623ae244d73ac2a3a5c109cc11667abf8be65bf"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "c71f9039d7def6dd8b2c527f231c4957b9e432fbd7fa2e9ac437e67847524d2e"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-linux-gnu-cxx11.tar.gz"
[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89b129daa7a5cffb68176356e3c152d6a75c3671"
os = "windows"

    [[SARSOP.download]]
    sha256 = "79456849a8e0373ff8252436541eeea54c36e00dacced91a020778d3d1513568"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-w64-mingw32-cxx03.tar.gz"
[[SARSOP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3877bc0138e401bf13c36c6dc63f92e08a05b269"
os = "windows"

    [[SARSOP.download]]
    sha256 = "78709fc419b07198d185864dbe56831660f760d9cf2f4728eaa357a2e5aab61e"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.i686-w64-mingw32-cxx11.tar.gz"
[[SARSOP]]
arch = "x86_64"
git-tree-sha1 = "9fae43389da9100f956b2c636d5b002069b07abe"
os = "macos"

    [[SARSOP.download]]
    sha256 = "cfd926f16cb74cbea0346e233fc5b29c47599d9b26ac9ddd04c8c0d4fb2ca8b2"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-apple-darwin.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d36608ac1bca75839d80c210e52a81e31da83d6"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "d634c5c7097576ed8fd0864d3e1305d8162642f5c96186d8966d6e1a6e620cf0"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dc495ed777b7a92379fc79a8ef3ba6a4ff0d511"
libc = "glibc"
os = "linux"

    [[SARSOP.download]]
    sha256 = "6fca7d17cfe07c16e2ba33e1e9cd4c0166bcd5a6b6d74e39fc6e6f3373619780"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d04e23d25259c6c6ff95b1d4da7384c13f1c821d"
os = "windows"

    [[SARSOP.download]]
    sha256 = "d9293db5a9652fab7f58d9e70a523f783d215652a573edc93e5accda48392664"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SARSOP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9b761df4aced3ca03c6751d6571b57e4f626e46"
os = "windows"

    [[SARSOP.download]]
    sha256 = "9d259c673ac85b30bd415d5731e1c48eaf862f6785dda66990a537a35ea0d662"
    url = "https://github.com/JuliaBinaryWrappers/SARSOP_jll.jl/releases/download/SARSOP-v0.96.0+0/SARSOP.v0.96.0.x86_64-w64-mingw32-cxx11.tar.gz"
