# Autogenerated wrapper script for SARSOP_jll for i686-w64-mingw32-cxx11
export polgraph, pomdpconvert, pomdpeval, pomdpsim, pomdpsol

JLLWrappers.@generate_wrapper_header("SARSOP")
JLLWrappers.@declare_executable_product(polgraph)
JLLWrappers.@declare_executable_product(pomdpconvert)
JLLWrappers.@declare_executable_product(pomdpeval)
JLLWrappers.@declare_executable_product(pomdpsim)
JLLWrappers.@declare_executable_product(pomdpsol)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        polgraph,
        "bin\\polgraph.exe",
    )

    JLLWrappers.@init_executable_product(
        pomdpconvert,
        "bin\\pomdpconvert.exe",
    )

    JLLWrappers.@init_executable_product(
        pomdpeval,
        "bin\\pomdpeval.exe",
    )

    JLLWrappers.@init_executable_product(
        pomdpsim,
        "bin\\pomdpsim.exe",
    )

    JLLWrappers.@init_executable_product(
        pomdpsol,
        "bin\\pomdpsol.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
